const addId = (item) => ({
  ...item,
  id: item.name.toLowerCase().split(' ').join('_'),
});

const d1 = [
  { name: 'Aurora' },
  { name: 'TOMM¥ €A$H' },
  { name: 'Boys Noize' },
  { name: 'Mura Masa' },
  { name: 'Daria Zawiałow' },
  { name: 'Rasmentalism' },
  { name: 'Schafter' },
  { name: 'Bedoes' },
  { name: 'Baasch Live' },
  { name: 'Vito Bambino' },
  { name: 'Chocolate Puma' },
  { name: 'Tchami' },
  { name: 'Julia Pośnik' },
  { name: 'FUKAJ' },
  { name: 'Miętha' },
  { name: 'Dillinja' },
  { name: 'Dirty Doe' },
  { name: 'Kanine' },
  { name: 'Tekitoka' },
  { name: 'Deedrah' },
  { name: 'Dzida' },
  { name: 'Egorythmia' },
  { name: 'Havaya' },
  { name: "Catz 'n Dogz" },
  { name: 'Glasse' },
  { name: 'La Fleur' },
  { name: 'Rodriguez Jr.' },
].map(addId);

const d2 = [
  { name: 'Alan Walker' },
  { name: 'Purple Disco Machine' },
  { name: 'Sam Feldt Live' },
  { name: 'slowthai' },
  { name: 'Pezet' },
  { name: 'Princess Nokia' },
  { name: 'Kiasmos DJ Set' },
  { name: 'sanah' },
  { name: 'Kwiat Jabłoni' },
  { name: 'Kerala Dust Live' },
  { name: 'Jan-Rapowanie' },
  { name: 'Jax Jones' },
  { name: 'Krzysztof Zalewski' },
  { name: 'KAMP!' },
  { name: 'Zdechły Osa' },
  { name: 'Kacperczyk' },
  { name: 'Bass Astral x Igo' },
  { name: 'Dillon' },
  { name: 'Jan Blomqvist & Band' },
  { name: 'Agoria' },
  { name: 'EINMUSIK' },
  { name: 'Some Minds' },
  { name: 'BOg' },
  { name: 'Bifidus Aktif' },
  { name: 'Kove' },
  { name: 'Keeno' },
  { name: 'Emperor' },
  { name: 'DJ Hype' },
  { name: 'Protest' },
  { name: 'Wonter' },
  { name: 'Wax' },
  { name: 'Jedimaster' },
  { name: 'Jot' },
  { name: 'Laughing Buddha' },
  { name: 'Transwave' },
  { name: 'Electronic Elephant' },
  { name: 'Enigmatic' },
  { name: 'Esther Silex' },
  { name: 'Kapoor' },
  { name: 'Mira b2b Chris Schwarzwälder' },
  { name: 'Rampue Live' },
  { name: 'Soukie & Windish' },
  { name: 'Igor Marijuan' },
].map(addId);

const d3 = [
  { name: 'Paul Kalkbrenner' },
  { name: 'Kungs' },
  { name: 'Mata' },
  { name: 'Bakermat' },
  { name: 'Ralph Kaminski' },
  { name: 'Mery Spolsky' },
  { name: 'The Blaze DJ Set' },
  { name: 'Kayah & Bregović' },
  { name: 'Sobel' },
  { name: 'Żabson' },
  { name: 'Sonbird' },
  { name: 'Sohn' },
  { name: 'Tymek' },
  { name: 'CatchUp & Hodak' },
  { name: 'Bloo Crane' },
  { name: 'Naviband' },
  { name: 'Ummet Ozcan' },
  { name: 'JWP/BC' },
  { name: 'Victor Ruiz' },
  { name: 'Handra' },
  { name: 'N O I' },
  { name: 'AL/SO' },
  { name: 'Bad Company UK' },
  { name: 'DJ Marky + MC GQ' },
  { name: 'Harriet Jaxxon' },
  { name: 'Hash' },
  { name: 'Greenhouse Effect' },
  { name: 'Phace' },
  { name: 'POGAN' },
  { name: 'ROS addiction' },
  { name: 'Tilt' },
  { name: 'Tom Encore' },
  { name: 'Unglued' },
  { name: 'CJ ART' },
  { name: 'Dreddy' },
  { name: 'Gaudium' },
  { name: 'Koda Kade' },
  { name: 'Magik' },
  { name: 'Main Ape' },
  { name: 'Primal' },
  { name: 'Tromesa' },
  { name: 'Deaf Can Dance' },
  { name: 'Eelke Kleijn' },
  { name: 'Oceanvs Orientalis Live' },
  { name: 'Parra for Cuva Live' },
  { name: 'Piotr HO b2b KUAK' },
  { name: 'Raidho b2b Foxall' },
  { name: 'Satori Live' },
  { name: 'Skarby DJ set' },
  { name: 'WhoMadeWho Hybrid' },
].map(addId);

const d4 = [
  { name: 'Kygo' },
  { name: 'Ofenbach' },
  { name: 'Robin Schulz' },
  { name: 'Nothing But Thieves' },
  { name: 'Smith & Thell' },
  { name: 'OIO' },
  { name: 'Undadasea' },
  { name: 'PRO8L3M' },
  { name: 'Hania Rani' },
  { name: 'Matisse & Sadko' },
  { name: 'Kazy Lambist' },
  { name: 'Miły ATZ' },
  { name: 'James Bay' },
  { name: 'Sokół' },
  { name: 'Janusz Walczuk' },
  { name: 'Mrozu' },
  { name: 'Natalia Przybysz' },
  { name: 'Jan Serce' },
  { name: 'Rysy' },
  { name: 'Enrico Sangiuliano' },
  { name: 'Denis Horvat' },
  { name: 'Cocolino' },
  { name: 'Krzyku' },
  { name: 'Sick' },
  { name: 'Mampi Swift' },
  { name: 'MAD /Cannabeatz/' },
  { name: 'Atom' },
  { name: 'adamformat. /' },
  { name: 'A.M.C' },
  { name: 'BUHHAJ' },
  { name: 'Document One + MC Felon' },
  { name: 'Ferro' },
  { name: 'Friction' },
  { name: 'Ginee' },
  { name: 'Maduk' },
  { name: 'Mia Twin' },
  { name: 'Captain Hook' },
  { name: 'Eitan Reiter Live' },
  { name: 'Jara Luca' },
  { name: 'Nois' },
  { name: 'Out of Orbit live' },
  { name: 'SourOne' },
  { name: 'Be Svendsen Live' },
  { name: 'Behrouz' },
  { name: 'Commander Love' },
  { name: 'El Mundo' },
  { name: 'Filip Sonik b2b Mihvu' },
  { name: 'Marcus Meinhardt' },
  { name: 'Tiga' },
  { name: 'Worakls Live' },
].map(addId);
